version: '3.3'
services:
  db:
    container_name: 'docker-wp-dev-db'
    image: 'mariadb'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  wordpress:
    container_name: 'docker-wp'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '80:80'
    volumes:
      - './wordpress:/var/www/html'
      - './plugins:/var/www/html/wp-content/plugins'
      - './themes:/var/www/html/wp-content/themes'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"